### ISSUE TITLE
Drop support of Python2

### ISSUE THREAD

**Issue by nilason** [ctypesgen/ctypesgen#112]
In January 2020, soon 2 (!) years ago, Python 2.7 reached [end-of-life](https://www.python.org/doc/sunset-python-2/).

The code of ctypesgen has been nicely ported to work excellent on Python 3!

However, there is still a CI test running on 2.7, implying the need to implement changes to work on legacy versions as well. Not only is this a real PITA to implement changes, it seems to me to be absolutely unnecessary and hampering improvements.

May I suggest to totally drop support for Python 2, starting with removing the CI test with 2.7.

**Comment by davidjamesca** [comment]
Updated & landed. The documentation states that Python 3.7 or later is
required.

If Python 3.8 and 3.9 tests are no-ops, we should probably delete them from
CI no? Is there any way to get them working, or maybe they support some
other newer Python versions?

**Comment by davidjamesca** [comment]
On Mon, Oct 11, 2021 at 8:21 AM David James ***@***.***> wrote:

> Updated & landed. The documentation states that Python 3.7 or later is
> required.
>
> If Python 3.8 and 3.9 tests are no-ops, we should probably delete them
> from CI no? Is there any way to get them working, or maybe they support
> some other newer Python versions?
>
I removed Python3.8 and 3.9 from CI. If there's any way to support newer
versions of Python in CI, I'd love to add it.

**Comment by nilason** [comment]
> Fixed

Great, thanks!
