### ISSUE TITLE
ctypesgen traits C long  as python float

### ISSUE THREAD

**Issue by novikauanton** [ctypesgen/ctypesgen#128]
### description
ctypesgen traits C `long`  as python `float`

### example

```
$ echo '#define LONG_VAL 0L' > long_val.h

$ ctypesgen long_val.h -o long_val.py

$ grep LONG_VAL long_val.py
    LONG_VAL = 0.0

$ python3 -c 'import long_val;print("type: `{}`, val: `{}`".format(long_val.LONG_VAL, type(long_val.LONG_VAL)))'
type: `0.0`, val: `<class 'float'>`

```

### version 

```
$ ctypesgen --version
1.0.2
```

**Comment by mara004** [comment]
So you think long should be treated as `int` rather than `float`?

**Comment by nilason** [comment]
> So you think long should be treated as `int` rather than `float`?

It is a integer constant, which is not yet supported in ctypesgen. The same with floating constants.

**Comment by nilason** [comment]
Looking at the code a bit closer, there is some support but perhaps not full.
However, `0L` is not a valid integer constant, see eg. https://en.cppreference.com/w/c/language/integer_constant.

**Comment by novikauanton** [comment]
@mara004 yes, it must be treated as int.
Same syntax was supported by python2:
```
$ python2.7 -c 'print(type(0L))'
<type 'long'>
```

But in python3 it was unified to int:

https://docs.python.org/3.0/whatsnew/3.0.html#integers
https://www.python.org/dev/peps/pep-0237/
 


@nilason  Could you please share a quote, why do you think it is not valid?

```
An integer constant is a non-lvalue expression of the form
    * decimal-constant integer-suffix(optional)
    * decimal-constant is a non-zero decimal digit (1, 2, 3, 4, 5, 6, 7, 8, 9), followed by zero or more decimal digits (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
    * integer-suffix, if provided, may contain one or both of the following (if both are provided, they may appear in any order):
        * unsigned-suffix (the character u or the character U)
        * long-suffix (the character l or the character L) or the long-long-suffix (the character sequence ll or the character sequence LL) (since C99)
```

So `0L` consists of   decimal-constant `0` and  long-suffix of single character `L` and looks like a valid long integer constant.

**Comment by nilason** [comment]
Yes, a literal starting with a `0` is supposed to be either a hex- (`0x`) octal- (`0`) or binary (`0b`) constant, a decimal constant starts with [1-9]. However compilers sort this out anyway, a zero is a zero no matter the radix.

Indeed, this is a bug/limitation of present code.

**Comment by nilason** [comment]
@mara004 
#131 fixes this issue, and more. Would be great if you could test it.

**Comment by mara004** [comment]
@nilason As I'm not the original reporter, I guess you primarily intended to ping @novikauanton ?

**Comment by nilason** [comment]
> @nilason As I'm not the original reporter, I guess you primarily intended to ping @novikauanton ?

Sorry about that, yes I meant to address this to @novikauanton.

**Comment by novikauanton** [comment]
@nilason, yes it fixed the issue with long literal.

Only one note `--version` argument is not longer available.

```
$ virtualenv venv --python python3.6

$ source venv/bin/activate

$ pip install git+https://github.com/nilason/ctypesgen.git@update_cgrammar

$ ctypesgen --version
    Usage: ctypesgen [options] /path/to/header.h ...

    ctypesgen: error: no such option: --version

$ which ctypesgen
    /home/user/ctypesgen_header_test/venv/bin/ctypesgen

$ echo '#define LONG_VAL 0L' > long_val.h

$ ctypesgen long_val.h -o long_val.py

$ grep LONG_VAL long_val.py
    LONG_VAL = 0

$ python -c 'import long_val;print("val: `{}`, type: `{}`".format(long_val.LONG_VAL, type(long_val.LONG_VAL)))'
    val: `0`, type: `<class 'int'>`

```

**Comment by nilason** [comment]
> @nilason, yes it fixed the issue with long literal.
 
Thanks for testing!

> Only one note `--version` argument is not longer available.

Pretty sure that is not related to #131 , as potentially related files for that are not touched.
However, following works for me on local **git** repo dir:
```
cd ctypesgen-repo-dir
./run.py --version
1.0.2-74-gc572d94
```
