### ISSUE TITLE
env python2.7 

### ISSUE THREAD

**Issue by yongjames** [ctypesgen/ctypesgen#130]
hi, I am a newbie and want to ask a simple question：Must the running environment be Pthon3？and does python2.7 compile properly?

With reference to：https://github.com/ctypesgen/ctypesgen/wiki/Creating-a-standalone-ctypesgen-executable-binary#1-start-a-python3-virtual-environment

**Comment by TheCodeArtist** [comment]
While `ctypesgen` may still work with Python2.7,   
Python3 is recommended/supported.   

https://github.com/ctypesgen/ctypesgen/wiki/Getting-Started#requirements
> Only 2 requirements:
> 
>     - Python, at least version 3.7
>     - A C pre-compiler, if you have a C compiler installed such as GCC you already have one


For more details of topic, checkout the discussion in https://github.com/ctypesgen/ctypesgen/issues/112.
