### ISSUE TITLE
Wrong generation from linux kernel header

### ISSUE THREAD

**Issue by void0red** [ctypesgen/ctypesgen#145]
When struct name is a **keyword** in python, the generated file cannot be imported.
e.g. **class**, https://elixir.bootlin.com/linux/latest/source/include/linux/device/class.h#L54

may be we should add some prefix or suffix to avoid this?

**Comment by mara004** [comment]
ctypesgen already has a mechanism to handle naming conflicts.
I never really tested it myself, but assuming this code works, I guess appending `keyword.kwlist` to the reserved names table in `processor/operations.py` should do.

**Comment by mara004** [comment]
Hmm, actually ctypesgen is supposed to have a mechanism for this already:
https://github.com/ctypesgen/ctypesgen/blob/deb059ee499c6c2335922afc1e7159013e017c9d/ctypesgen/processor/operations.py#L189-L190
`keyword.kwlist` is provided by python's stdlib and should contain all keywords.
Maybe it's not working correctly, though? I'll look into this later.

**Comment by mara004** [comment]
Ah, I think I found the culprit.
The reason that it doesn't work is that it was never called, due to a misaligned if-check:

https://github.com/ctypesgen/ctypesgen/blob/deb059ee499c6c2335922afc1e7159013e017c9d/ctypesgen/__main__.py#L277-L284
https://github.com/ctypesgen/ctypesgen/blob/deb059ee499c6c2335922afc1e7159013e017c9d/ctypesgen/processor/pipeline.py#L63-L65

**Comment by mara004** [comment]
This issue was introduced with commit https://github.com/ctypesgen/ctypesgen/commit/f12737e5bb1e6075023ef165b63e7bdb46581ef7
It updated another occurrence correctly, but evidently missed this one.

**Comment by mara004** [comment]
Hmm, that said, the name resolver seems to *prefix* with underscore. Maybe suffixing would be better? - because a leading underscore implies being non-public, which does not follow logically out of a naming conflict.

**Comment by mara004** [comment]
Also, from re-reading the code, it turns out the conflict resolver in its current form isn't very useful - it excludes all dependants, instead of actually renaming them 😖
