### ISSUE TITLE
Strange <built-in> error in console

### ISSUE THREAD

**Issue by RobbyChapman** [ctypesgen/ctypesgen#151]
I wouldn't necessarily call this an issue, as ctypesgen works great, and still produces the expected output, but for some reason when running the utility I always see the following messages logged:

`ctypesgen --all-errors --show-long-errors Foo.h > log.txt`

```
WARNING: No libraries specified
INFO: Status: Preprocessing C:\Users\SOME~1.USR\AppData\Local\Temp\tmptxoxgoa3.h
INFO: Status: gcc -E -U __GNUC__ -dD "-Dinline=" "-D__inline__=" "-D__extension__=" "-D__const=const" "-D__asm__(x)=" "-D__asm(x)=" "-DCTYPESGEN=1" "C:\Users\SOME~1.USR\AppData\Local\Temp\tmptxoxgoa3.h"
INFO: Status: Parsing C:\Users\SOME~1.USR\AppData\Local\Temp\tmptxoxgoa3.h
ERROR: <built-in>:230: Syntax error at '\n'
ERROR: <built-in>:231: Syntax error at '\n'
ERROR: <built-in>:232: Syntax error at '\n'
ERROR: <built-in>:233: Syntax error at '\n'
ERROR: <built-in>:234: Syntax error at '\n'
ERROR: <built-in>:235: Syntax error at '\n'
ERROR: <built-in>:236: Syntax error at '\n'
ERROR: <built-in>:237: Syntax error at '\n'
INFO: Status: Processing description list.
WARNING: Could not parse macro "#define __stdcall __attribute__ ( ( __stdcall__ ) )"
WARNING: Could not parse macro "#define __fastcall __attribute__ ( ( __fastcall__ ) )"
WARNING: Could not parse macro "#define __thiscall __attribute__ ( ( __thiscall__ ) )"
WARNING: Could not parse macro "#define __cdecl __attribute__ ( ( __cdecl__ ) )"
WARNING: Could not parse macro "#define _stdcall __attribute__ ( ( __stdcall__ ) )"
WARNING: Could not parse macro "#define _fastcall __attribute__ ( ( __fastcall__ ) )"
WARNING: Could not parse macro "#define _thiscall __attribute__ ( ( __thiscall__ ) )"
WARNING: Could not parse macro "#define _cdecl __attribute__ ( ( __cdecl__ ) )"
WARNING: Could not parse macro "#define __declspec(x) __attribute__ ( ( x ) )"
WARNING: Macro "__has_include" depends on an unknown identifier "__has_include__". Macro "__has_include" will not be output
WARNING: Macro "__has_include_next" depends on an unknown identifier "__has_include_next__". Macro "__has_include_next" will not be output
WARNING: Identifier pasting is not supported by ctypesgen. Macro "__INTMAX_C" will not be output
WARNING: Identifier pasting is not supported by ctypesgen. Macro "__UINTMAX_C" will not be output
WARNING: Identifier pasting is not supported by ctypesgen. Macro "__INT64_C" will not be output
WARNING: Identifier pasting is not supported by ctypesgen. Macro "__UINT32_C" will not be output
WARNING: Identifier pasting is not supported by ctypesgen. Macro "__UINT64_C" will not be output
WARNING: Macro "__USER_LABEL_PREFIX__" depends on an unknown identifier "_". Macro "__USER_LABEL_PREFIX__" will not be output
INFO: Status: Writing to stdout.
INFO: Status: Wrapping complete.
```

The header I'm passing in is just a sample to demonstrate the issue:
```
#ifndef FOO_H
#define FOO_H

typedef struct
{
   int test;
} Foo_t;

#endif
```

I've attached the log, and associated header file as well.

I'm going to debug the issue on my end but, one interesting find is that, if invoking the preprocessor directly, I don't see any errors. I've attached the log for that as well.

`gcc -E -U __GNUC__ -dD "-Dinline=" "-D__inline__=" "-D__extension__=" "-D__const=const" "-D__asm__(x)=" "-D__asm(x)=" "-DCTYPESGEN=1" "Foo.h"`

I have a feeling that ctypesgen might be picking up on something wrong with my environment. For that reason I put a couple of details below:

- Ctypesgen Version: 1.0.2
- Python Version: 3.10.6
- GCC Version: 6.3.0.1
- OS Version: Windows 11 10.0.22000

**GCC Details**
`gcc -v`

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/6.3.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --target=mingw32 --with-gmp=/mingw --with-mpfr --with-mpc=/mingw --with-isl=/mingw --prefix=/mingw --disable-win32-registry --with-arch=i586 --with-tune=generic --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-6.3.0-1' --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --enable-libgomp --disable-libvtv --enable-nls
Thread model: win32
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)
```

**Logs**
[gcc_log.txt](https://github.com/ctypesgen/ctypesgen/files/9726897/gcc_log.txt)
[ctypes_log.txt](https://github.com/ctypesgen/ctypesgen/files/9726898/ctypes_log.txt)

Let me know if anything jumps out. 

Thanks!

**Comment by nilason** [comment]
This is unfortunately "normal" behaviour of ctypesgen. The reason is foremost its limited parser capabilities with C language extensions. Those are often found in system library header files and usually they are the ones causes the warnings. In general this kind of warnings may be ignored.
If you can, I advice you to use/test the ctypesgen master version found here. There are a bunch of improvements, see [CHANGELOG](https://github.com/ctypesgen/ctypesgen/blob/master/CHANGELOG.md), even though these warnings still are there.

**Comment by RobbyChapman** [comment]
Thanks for the quick follow-up! No problem, I can always silence the output. And thanks for the heads up about the master branch, I'll pull it down and see how things run. We can mark this one as closed.
