### ISSUE TITLE
v1.1.0 will ignore "short"? 

### ISSUE THREAD

**Issue by jfongattw** [ctypesgen/ctypesgen#156]
I found in v1.1.0, the added condition in file ctypesparser.py 
            elif specifier == "short":
                longs = -1
will cause the following line in header file be ignored
    typedef unsigned short WORD

--Jach

**Comment by nilason** [comment]
Just tested on Mac with:

```c
typedef unsigned short WORD;
```

which generates:

```py
WORD = c_ushort# /Users/...
```

which is what I expect from it.

**Comment by nilason** [comment]
@jfongattw Could you share a minimal code which reproduces your issue.
I also assume you're working on Windows...

**Comment by jfongattw** [comment]
Yes, I am working on Windows 8.1 x64:-)

Using the ctypesgen-master\demo\demolib.h as an example. Adding the following two lines before the function prototype,

-----
typedef unsigned char uint8;
typedef unsigned short uint16;

int trivial_add(int a, int b);
-----

and generates the code by running
e:\Works\Python\ctypesgen-master\demo>py ../run.py -o pydemolib.py -l demolib.dll demolib.h

There, in pydemolib.py, only the uint8 showing up.

-----
uint8 = c_ubyte# e:\\Works\\Python\\ctypesgen-master\\demo\\demolib.h: 6

# e:\\Works\\Python\\ctypesgen-master\\demo\\demolib.h: 9
if _libs["demolib.dll"].has("trivial_add", "cdecl"):
    trivial_add = _libs["demolib.dll"].get("trivial_add", "cdecl")
    trivial_add.argtypes = [c_int, c_int]
    trivial_add.restype = c_int
-----

Note: In the above experiment, I only update the ctypesparser.py file in my working ctypesgen version(dated 2022-04-28). Is it the possible reason causing this error?

**Comment by nilason** [comment]
> Note: In the above experiment, I only update the ctypesparser.py file in my working ctypesgen version(dated 2022-04-28). Is it the possible reason causing this error?

Most likely. The specific "short int" fix covers two source files. I advice you to (always) make a proper update (download) of ctypesgen source.

**Comment by jfongattw** [comment]
Yes, you are right. I missed the other file during the update of my package.
Sorry to bother you:-( Thank you!

**Comment by nilason** [comment]
No problem, please close this issue if "solved".
