### ISSUE TITLE
Switch from optparse to argparse

### ISSUE THREAD

**Issue by mara004** [ctypesgen/ctypesgen#159]
Ctypesgen still uses the deprecated optparse. It would be good to switch to argparse at some point.
From Python's docs:

> Deprecated since version 3.2: The [optparse](https://docs.python.org/3/library/optparse.html#module-optparse) module is deprecated and will not be developed further; development will continue with the [argparse](https://docs.python.org/3/library/argparse.html#module-argparse) module.

**Comment by nilason** [comment]
Solved with #161. Closing.
