### ISSUE TITLE
Cleanup broken handling of "-W,..."

### ISSUE THREAD

**Issue by TheCodeArtist** [ctypesgen/ctypesgen#164]
*(Explicitly raising this issue to discuss and figure out 
how to proceed with addressing the potentially broken handling of the the `-W` cmd-line parameter.)*

----

It was recently discovered that the code to handle `-W,...` in ctypesgen, is potentially broken.
The existing implementation to handle `-W,...` does not parse it properly.

- Based on [recent code-review](https://github.com/ctypesgen/ctypesgen/pull/161/commits/b07a872b3f178a0af91599422c18048560ba6bea#r1037366532).

Also, the related code/logic might never have been used/verified (since 2008).
- Based on the [**history and comments**](https://github.com/ctypesgen/ctypesgen/pull/161/commits/b07a872b3f178a0af91599422c18048560ba6bea#r1032791936).

## Problem

- The currently active set of developers did not happen to rely on `-W,..` handling by ctypesgen.
 
- Also, it is not clear if any users of ctypesgen ever relied on `-W` handling of ctypesgen.
    - As the handling of `-W,...` does NOT do something meaningful ([since 2008](https://github.com/ctypesgen/ctypesgen/commit/ece4eaaff0a8af3877a1081febccc48062272c06#)),
      but there have been no issues / error reports on this, right?

The code to handle `-W` (and subsequent code/logic within ctypesgen that is triggered upon encountering `-W` on the cmd-line) is now acting as a blocker against further improving `ctypesgen`. For example switching to a modern argument-list parser `optparse` instead of `argparse`. 

Also, it is a burden,
to maintain/upgrade the bit of code downstream of `-W` handling
especially if it doesn't accomplish anything meaningful anyway.

## How to we proceed to clean this up?

Here's one approach i could think of...

1. Identify the parts of code that attempt to handle `-W` but appear to do nothing meaningful or useful?
    - Searching for libraries implemented [here](https://github.com/ctypesgen/ctypesgen/blob/5396d03e76ff0aab2df557bdc9bddbdd5909d304/ctypesgen/processor/pipeline.py#L66).
    - Called as part of the main sequence [here](https://github.com/ctypesgen/ctypesgen/blob/5396d03e76ff0aab2df557bdc9bddbdd5909d304/ctypesgen/processor/pipeline.py#L52) (via [this](https://github.com/ctypesgen/ctypesgen/blob/5396d03e76ff0aab2df557bdc9bddbdd5909d304/ctypesgen/processor/__init__.py#L12)).
    - *<any other other `-W,..`-related broken/dead code?>*

2. Obtain feedback from all ctypesgen developers and users 
if anyone ever has relied on ctypesgen parsing `-W` and doing something meaningful with it ?
    - How do we obtain this feedback from the users? 🤔 

3. *< Anything else we can do here, before step 4?... >*

4.  Mark `-W` as deprecated and update cmd-line param handler to print a warning if `-W` is passed to `ctypesgen`.
Also, maybe can include a line in the warning message to report an issue here on Github if some user was indeed relying on some side-effect of the legacy behavior of `ctypesgen` when passed `-W,...` to it over the cmd-line.

----

_(i apologize if this is a bit too long. i have tried to summarise everything i could figure out on this topic here in one place.
Hopefully someone can suggest the best course of action.)_

**Comment by mara004** [comment]
This is simply broken, dead code that should be removed, and there's no point making such a fuss about it, you're only wasting your time.
If anyone ever needs to pass further arguments down the processing pipeline, then it should be re-implemented cleanly.

**Comment by TheCodeArtist** [comment]
> there's no point making such a fuss about it, you're only wasting your time.

Agreed. It is very likely i am overthinking it. 🙂 
As the discussions on the other PRs did not arrive at any conclusion,
i thought of having all this info here in one place in hopes that it might help the maintainers make a decision.

Hopefully, there's consensus soon on this topic.
_(and i hope that it is to remove unused/dead-code)_

> This is simply broken, dead code that should be removed

Yep. Sounds like that's the only option left.
_(as leaving this dead-code around is hindering further development/upgrade of other functional parts of ctypesgen)_

----

One of the next steps (i believe) that can help with this effort 
would be having a clearly identified set of files and functions of currently unused dead-code.
_(all the way from the broken initial `-W` parameter handling, to entire unused functions that were supposed to be called if `-W` were passed, but were never triggered)_

That is something which we need to figure out in any case to clean it up properly.

**Comment by mara004** [comment]
@nilason Since #161 was merged, I think this can be closed, too.

**Comment by nilason** [comment]
> @nilason Since #161 was merged, I think this can be closed, too.

Correct, thanks! Closing.
