### ISSUE TITLE
#define a char

### ISSUE THREAD

**Issue by ninibay** [ctypesgen/ctypesgen#167]
in c header:
`#define CHAR3 '3'`

generated in py
`CHAR3 = '3'`

CHAR3 is a char but in py is a string and not work when assignment
maybe below is better in py?

`CHAR3 = b'3'`

**Comment by mara004** [comment]
Agreed, `#define char ...` should be translated to a b-string.

**Comment by nilason** [comment]
I believe this is a regression/change with version 1.1.0, in earlier version(s) it used to result in a byte literal.

But I wonder what would be the best alternative, maybe convert it to an integer? #149 reports on failure with byte literal during bit-shift operations, e.g.

```py
>>> CHAR3 = b'3'
>>> CHAR3 << 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for <<: 'bytes' and 'int'
# but
>>> int.from_bytes(CHAR3, byteorder='little') << 1
102
```

**Comment by mara004** [comment]
If using int, would a function expecting char auto-cast to that?

**Comment by nilason** [comment]
> If using int, would a function parameter expecting char auto-cast it to that?

That is not the way to go, `b'[char]'` is needed. And bit-shifting can not be supported through auto-generated code.
#171 addresses this.


From [Python Docs](https://docs.python.org/3/library/ctypes.html#fundamental-data-types):

| ctypes type | C type | Python type |
| --- | --- | --- |
| c_char | char | 1-character bytes object |
